skladProduktuNaturalnegoOptions = [
  {
    name: "obornik bydlęcy",
    azot: 0.45,
    fosfor: 0.3,
    potas: 0.5,
    isObornik: true,
  },
  {
    name: "obornik świński",
    azot: 0.45,
    fosfor: 0.3,
    potas: 0.6,
    isObornik: true,
  },
  {
    name: "obornik koński",
    azot: 0.58,
    fosfor: 0.28,
    potas: 0.5,
    isObornik: true,
  },
  {
    name: "obornik mieszany",
    azot: 0.5,
    fosfor: 0.3,
    potas: 0.5,
    isObornik: true,
  },
  {
    name: "obornik od kur (chów ściółkowy)",
    azot: 1.3,
    fosfor: 0.4,
    potas: 0.6,
    isObornik: true,
  },
  {
    name: "gnojowica bydlęca gęsta",
    azot: 0.36,
    fosfor: 0.2,
    potas: 0.4,
    isObornik: false,
  },
  {
    name: "gnojowica bydlęca średnia",
    azot: 0.3,
    fosfor: 0.1,
    potas: 0.5,
    isObornik: false,
  },
  {
    name: "gnojowica bydlęca rzadka",
    azot: 0.19,
    fosfor: 0.05,
    potas: 0.4,
    isObornik: false,
  },
  {
    name: "gnojowica świńska gęsta",
    azot: 0.44,
    fosfor: 0.3,
    potas: 0.3,
    isObornik: false,
  },
  {
    name: "gnojowica świńska średnia",
    azot: 0.35,
    fosfor: 0.1,
    potas: 0.2,
    isObornik: false,
  },
  {
    name: "gnojowica świńska rzadka",
    azot: 0.25,
    fosfor: 0.75,
    potas: 0.15,
    isObornik: false,
  },
  {
    name: "pomiot od kur (chów klatkowy)",
    azot: 1.6,
    fosfor: 1.5,
    potas: 0.8,
    isObornik: false,
  },
  {
    name: "słoma pszenicy",
    azot: 0.7,
    fosfor: 0.25,
    potas: 1.4,
    isObornik: false,
  },
  {
    name: "słoma pszenżyta",
    azot: 0.6,
    fosfor: 0.3,
    potas: 1.5,
    isObornik: false,
  },
  { name: "słoma żyta", azot: 0.7, fosfor: 0.35, potas: 1.7, isObornik: false },
  {
    name: "słoma jęczmienia paszowego",
    azot: 0.75,
    fosfor: 0.25,
    potas: 1.6,
    isObornik: false,
  },
  {
    name: "słoma jęczmienia browarnego",
    azot: 0.65,
    fosfor: 0.25,
    potas: 1.6,
    isObornik: false,
  },
  { name: "słoma owsa", azot: 1.0, fosfor: 0.45, potas: 2.6, isObornik: false },
  {
    name: "słoma kukurydzy ziarnowej",
    azot: 1.5,
    fosfor: 0.5,
    potas: 3.0,
    isObornik: false,
  },
  {
    name: "resztki kukurydzy kiszonkowej",
    azot: 0.07,
    fosfor: 0.022,
    potas: 0.12,
    isObornik: false,
  },
  {
    name: "słoma rzepaku",
    azot: 1.6,
    fosfor: 0.6,
    potas: 4.0,
    isObornik: false,
  },
  {
    name: "słoma grochu",
    azot: 1.6,
    fosfor: 0.35,
    potas: 1.8,
    isObornik: false,
  },
  {
    name: "słoma łubinu",
    azot: 1.5,
    fosfor: 0.55,
    potas: 1.6,
    isObornik: false,
  },
  { name: "słoma soi", azot: 1.6, fosfor: 0.5, potas: 2.0, isObornik: false },
  {
    name: "słoma bobiku",
    azot: 1.8,
    fosfor: 0.45,
    potas: 2.2,
    isObornik: false,
  },
  {
    name: "resztki po buraku",
    azot: 0.3,
    fosfor: 0.08,
    potas: 0.5,
    isObornik: false,
  },
  {
    name: "resztki po ziemniaku",
    azot: 0.1,
    fosfor: 0.02,
    potas: 0.18,
    isObornik: false,
  },
];
